[mypy]
python_version = 3.12
plugins = mypy_django_plugin.main
strict_optional = True
warn_unused_ignores = True
warn_redundant_casts = True
show_error_codes = True
ignore_missing_imports = True

[mypy.plugins.django-stubs]
django_settings_module = config.settings.dev

[mypy-tests.*]
ignore_errors = True

[mypy-*.migrations.*]
ignore_errors = True
